const TermsOfServicePage = () => (
  <div className="max-w-3xl mx-auto prose prose-sm dark:prose-invert">
    <h1>Terms of Service</h1>
    <p><strong>Last Updated:</strong> March 22, 2026</p>

    <h2>1. Agreement to Terms</h2>
    <p>By accessing or using our web application, you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use our application.</p>

    <h2>2. Description of Service</h2>
    <p>TaskFlow is a personal task management web application that allows users to create, organize, and prioritize tasks. The application includes features such as task creation, editing, deletion, calendar integration, client tagging, time estimation, description fields, and intelligent task prioritization powered by Large Language Models (LLMs).</p>

    <h2>3. User Accounts &amp; Responsibilities</h2>
    <p>Our application is designed for single-user operation (superuser only). No user accounts or authentication are required.</p>
    <p>You are solely responsible for maintaining the confidentiality of any information you provide to us, including but not limited to your LLM API keys or configuration details.</p>
    <p>You are responsible for all activity that occurs under your use of the application, whether or not authorized by you.</p>

    <h2>4. Intellectual Property</h2>
    <ul>
      <li><strong>Our Content:</strong> The content of our application, including but not limited to text, graphics, logos, images, and software, is the property of Giovanni Turri and is protected by copyright, trademark, and other intellectual property laws.</li>
      <li><strong>Your Content:</strong> You retain ownership of the task data you create and store within our application. However, by using our application, you grant us a non-exclusive, royalty-free license to use, reproduce, and display your task data solely for the purpose of providing and improving our services.</li>
      <li><strong>LLM Output:</strong> You acknowledge that any output generated by the LLMs integrated into our application is not guaranteed to be accurate, complete, or suitable for any particular purpose. We are not responsible for the content generated by LLMs.</li>
    </ul>

    <h2>5. Acceptable Use Policy</h2>
    <p>You agree to use our application only for lawful purposes and in a manner that does not infringe on the rights of others. You shall not:</p>
    <ul>
      <li>Use our application to engage in any illegal or harmful activity.</li>
      <li>Attempt to disrupt or interfere with the operation of our application.</li>
      <li>Circumvent any security measures implemented by us.</li>
      <li>Use our application in a manner that violates the terms of service of any third-party services (e.g., Google Calendar API).</li>
    </ul>

    <h2>6. Disclaimer of Warranties</h2>
    <p>OUR APPLICATION IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT. WE MAKE NO REPRESENTATIONS OR GUARANTEES ABOUT THE ACCURACY, RELIABILITY, SUITABILITY, OR AVAILABILITY OF OUR APPLICATION.</p>

    <h2>7. Limitation of Liability</h2>
    <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF YOUR USE OF OUR APPLICATION, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>

    <h2>8. Termination</h2>
    <p>We may terminate your access to our application at any time, for any reason or no reason. This does not affect your rights with respect to task data you created prior to termination, which you can export as described below.</p>

    <h2>9. Data Export &amp; Deletion</h2>
    <p>You may be able to export your task data from our application in a standard format. If you wish to delete your task data, please contact us at <a href="mailto:giovi.Turri9@gmail.com">giovi.Turri9@gmail.com</a>. We will make reasonable efforts to comply with your request.</p>

    <h2>10. Governing Law &amp; Dispute Resolution</h2>
    <p>These Terms shall be governed by and construed in accordance with applicable laws. Any disputes arising out of or relating to these Terms shall be resolved through appropriate legal channels.</p>

    <h2>11. Changes to Terms of Service</h2>
    <p>We may update these Terms from time to time. We will notify you of any changes by posting the updated Terms on our website or by sending you an email. Your continued use of our application after any such changes constitutes your acceptance of the revised Terms.</p>

    <h2>12. Contact Us</h2>
    <p>If you have any questions or concerns about these Terms of Service, please contact us at: <a href="mailto:giovi.Turri9@gmail.com">giovi.Turri9@gmail.com</a></p>
  </div>
);

export default TermsOfServicePage;
